# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='some',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
