# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import generate_qrcode.models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_qrcode', '0002_auto_20170930_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='some',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=generate_qrcode.models.upload_location),
        ),
    ]
